--[[
Groupes Neovim
Références :
- https://neovim.io/doc/user/syntax.html#highlight-groups
- https://neovim.io/doc/user/syntax.html#group-name
]]
local colors = require('colorscheme.clairobscur.colors')
local groups = {}

local function set_hl(name, map)
  map.force = map.force and true or nil
  map.cterm = map.cterm or {}
  vim.api.nvim_set_hl(0, name, map)
end

local function merge_tbl(src, dest)
  for k, v in pairs(src) do dest[k] = v end
end

--[[
Le système de couleurs est basé sur l'article "On the design of text editors"
de Nicolas P. Rougier.
Voir https://arxiv.org/abs/2008.06030 pour l'article
Et https://creativecommons.org/licenses/by/4.0/ pour la licence
]]
function groups.apply(opts)
  local palette = colors.palette(opts)
  -- https://neovim.io/doc/user/syntax.html#highlight-groups
  local highlight_groups = {
    ColorColumn = { link = 'Subtle' },
    Conceal = { link = 'Faded' },
    CurSearch = { link = 'Search' },
    lCursor = { bg = fg, fg = bg },
    CursorIM = { link = 'Cursor' },
    CursorColumn = { bg = palette.cursor },
    CursorLine = { bg = palette.cursor },
    Directory = { link = 'Strong' },
    DiffAdd = { link = 'Salient' },
    DiffChange = { link = 'Popout' },
    DiffDelete = { link = 'Faded' },
    DiffText = { fg = palette.salient, bold = true },
    DiffTextAdd = { link = 'DiffText' },
    EndOfBuffer = { link = 'NonText' },
    TermCursor = { reverse = true },
    ErrorMsg = { link = 'Critical' },
    StderrMsg = { link = 'ErrorMsg' },
    StdoutMsg = { link = 'NONE' },
    WinSeparator = { link = 'Normal' },
    Folded = { link = 'Strong' },
    FoldColumn = { bg = palette.bg, fg = palette.subtle },
    SignColumn = { bg = palette.bg, fg = palette.subtle },
    IncSearch = { link = 'Strong' },
    Substitute = { link = 'Search' },
    LineNr = { link = 'Faded' },
    LineNrAbove = { link = 'LineNr' },
    LineNrBelow = { link = 'LineNr' },
    CursorLineNr = { bg = palette.cursor, fg = palette.faded, bold = true },
    CursorLineFold = { bg = palette.cursor, fg = palette.subtle, bold = true },
    CursorLineSign = { bg = palette.cursor, fg = palette.subtle, bold = true },
    MatchParen = { link = 'Popout' },
    ModeMsg = { link = 'Strong' },
    MsgArea = {},
    MsgSeparator = { link = 'StatusLine' },
    MoreMsg = { link = 'Strong' },
    NonText = { link = 'Faded' },
    NormalFloat = { link = 'Pmenu' },
    FloatBorder = { link = 'WinSeparator' },
    FloatTitle = { link = 'Title' },
    FloatFooter = { link = 'Title' },
    NormalNC = { link = 'NONE' },
    Pmenu = { link = 'Subtle' },
    PmenuSel = { bg = palette.popout, fg = palette.strong, bold = true },
    PmenuKind = { link = 'Pmenu' },
    PmenuKindSel = { link = 'PmenuSel' },
    PmenuExtra = { link = 'Pmenu' },
    PmenuExtraSel = { link = 'Pmenu' },
    PmenuSbar = { bg = palette.faded, fg = palette.fg },
    PmenuThumb = { bg = palette.fg, fg = palette.faded },
    PmenuMatch = { link = 'Faded' },
    PmenuMatchSel = { bg = palette.popout, fg = palette.strong, bold = true },
    ComplMatchIns = { link = 'NONE' },
    Question = { link = 'Strong' },
    QuickFixLine = { bg = palette.cursor },
    Search = { link = 'Subtle' },
    SnippetTabstop = { link = 'Visual' },
    SpecialKey = { link = 'NonText' },
    SpellBad = { link = 'Popout' },
    SpellCap = { link = 'Popout' },
    SpellLocal = { link = 'Popout' },
    SpellRare = { link = 'Popout' },
    StatusLine = { bold = true, reverse = true },
    StatusLineNC = { reverse = true },
    StatusLineTerm = { link = 'StatusLine'},
    StatusLineTermNC = { link = 'StatusLineNC' },
    TabLine = { link = 'Subtle' },
    TabLineFill = { link = 'Subtle' },
    TabLineSel = { link = 'Strong' },
    Title = { link = 'Strong' },
    Visual = { link = 'Subtle' },
    VisualNOS = { link = 'Visual' },
    WarningMsg = { link = 'Popout' },
    Whitespace = { link = 'NonText' },
    WildMenu = { link = 'Salient' },
    WinBar = { link = 'Strong' },
    WinBarNC = { link = 'WinBar' },
    --  TODO Considérer les groupes User1 à User9 utilisés par statusline ou ruler
    --User1 = {},
    --User2 = {},
    --User3 = {},
    --User4 = {},
    --User5 = {},
    --User6 = {},
    --User7 = {},
    --User8 = {},
    --User9 = {},
    Menu = { link = 'Strong' },
    Scrollbar = { bg = palette.faded, fg = palette.fg },
    Tooltip = { link = 'Subtle' },
  }
  --https://neovim.io/doc/user/syntax.html#group-name
  local syntax_groups = {
    Comment = { link = 'Faded' },
    Constant = { link = 'Salient' },
    String = { link = 'Popout' },
    Character = { link = 'Constant' },
    Number = { link = 'Constant' },
    Boolean = { link = 'Constant' },
    Float = { link = 'Number' },
    Identifier = { link = 'Strong' },
    Function = { link = 'Identifier' },
    Statement = { link = 'Salient' },
    Conditional = { link = 'Statement' },
    Repeat = { link = 'Statement' },
    Label = { link = 'Statement' },
    Operator = { link = 'Statement' },
    Keyword = { link = 'Statement' },
    Exception = { link = 'Statement' },
    PreProc = { link = 'Salient' },
    Include = { link = 'PreProc' },
    Define = { link = 'PreProc' },
    Macro = { link = 'PreProc' },
    PreCondit = { link = 'PreProc' },
    Type = { link = 'Salient' },
    StorageClass = { link = 'Type' },
    Structure = { link = 'Type' },
    Typedef = { link = 'Type' },
    Special = { link = 'Popout' },
    SpecialChar = { link = 'Special' },
    Tag = { link = 'Special' },
    Delimiter = { link = 'Special' },
    SpecialComment = { link = 'Special' },
    Debug = { link = 'Special' },
    Underlined = { fg = palette.salient, underline = true },
    Ignore = { fg = bg },
    Error = { link = 'Popout' },
    Todo = { link = 'Salient' },
    Added = { link = 'Salient' },
    Changed = { link = 'Popout' },
    Removed = { link = 'Faded' },
  }
  -- https://neovim.io/doc/user/diagnostic.html#diagnostic-highlights
  local diagnostic_highlights = {
    DiagnosticError = { link = 'Critical' },
    DiagnosticWarn = { link = 'Popout'},
    DiagnosticInfo = { link = 'Normal' },
    DiagnosticHint = { link = 'Faded' },
    DiagnosticOk = { link = 'Salient' },
    DiagnosticVirtualTextError = { link = 'DiagnosticError' },
    DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
    DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
    DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
    DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
    DiagnosticVirtualLinesError = { link = 'DiagnosticError' },
    DiagnosticVirtualLinesWarn = { link = 'DiagnosticWarn' },
    DiagnosticVirtualLinesInfo = { link = 'DiagnosticInfo' },
    DiagnosticVirtualLinesHint = { link = 'DiagnosticHint' },
    DiagnosticVirtualLinesOk = { link = 'DiagnosticOk' },
    DiagnosticUnderlineError = { bg = palette.critical, fg = palette.bg, underline = true },
    DiagnosticUnderlineWarn = { fg = palette.popout, underline = true },
    DiagnosticUnderlineInfo = { bg = palette.bg, fg = palette.fg, underline = true },
    DiagnosticUnderlineHint = { fg = palette.faded, underline = true },
    DiagnosticUnderlineOk = { fg = palette.salient, underline = true },
    DiagnosticFloatingError = { link = 'DiagnosticError' },
    DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
    DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
    DiagnosticFloatingHint = { link = 'DiagnosticHint' },
    DiagnosticFloatingOk = { link = 'DiagnosticOk' },
    DiagnosticSignError = { link = 'DiagnosticError' },
    DiagnosticSignWarn = { link = 'DiagnosticWarn' },
    DiagnosticSignInfo = { link = 'DiagnosticInfo' },
    DiagnosticSignHint = { link = 'DiagnosticHint' },
    DiagnosticSignOk = { link = 'DiagnosticOk' },
    DiagnosticDeprecated,
    DiagnosticUnnecessary = { link = 'Comment' },
  }
  --https://neovim.io/doc/user/treesitter.html#treesitter-highlight-groups
  local treesitter_highlight_groups = {
    ['@variable'] = { link = 'Identifier' },
    ['@variable.builtin'] = { link = 'Special' },
    ['@variable.parameter'] = { link = 'Identifier' },
    ['@variable.parameter.builtin'] = { link = 'Special' },
    ['@variable.member'] = { link = 'Identifier' },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { link = 'Special' },
    ['@constant.macro'] = { link = 'Define' },
    ['@module'] = { link = 'Popout' },
    ['@module.builtin'] = { link = 'Special' },
    ['@label'] = { link = 'Label' },
    ['@string'] = { link = 'String' },
    ['@string.documentation'] = { link = 'Faded' },
    ['@string.regexp'] = { link = 'String' },
    ['@string.escape'] = { link = 'SpecialChar' },
    ['@string.special'] = { link = 'SpecialChar' },
    ['@string.special.symbol'] = { link = '@string.special' },
    ['@string.special.path'] = { link = '@string.special' },
    ['@string.special.url'] = { link = 'Underlined' },
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@boolean'] = { link = 'Boolean' },
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Float' },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { link = 'Special' },
    ['@type.definition'] = { link = 'Typedef' },
    ['@attribute'] = { link = 'Macro' },
    ['@attribute.builtin'] = { link = 'Special' },
    ['@property'] = { link = 'Identifier' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { link = 'Special' },
    ['@function.call'] = { link = '@function' },
    ['@function.macro'] = { link = 'Macro' },
    ['@function.method'] = { link = '@function' },
    ['@function.method.call'] = { link = '@function.method' },
    ['@constructor'] = { link = 'Special' },
    ['@operator'] = { link = 'Operator' },
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.coroutine'] = { link = '@keyword' },
    ['@keyword.function'] = { link = '@keyword' },
    ['@keyword.operator'] = { link = 'Keyword' },
    ['@keyword.import'] = { link = 'Include' },
    ['@keyword.type'] = { link = 'Structure' },
    ['@keyword.modifier'] = { link = '@keyword' },
    ['@keyword.repeat'] = { link = 'Repeat' },
    ['@keyword.return'] = { link = '@keyword' },
    ['@keyword.debug'] = { link = 'Debug' },
    ['@keyword.exception'] = { link = 'Exception' },
    ['@keyword.conditional'] = { link = 'Conditional' },
    ['@keyword.conditional.ternary'] = { link = '@keyword.conditional' },
    ['@keyword.directive'] = { link = 'PreProc' },
    ['@keyword.directive.define'] = { link = 'Define' },
    ['@punctuation'] = { link = 'Delimiter' },
    ['@punctuation.delimiter'] = { link = '@punctuation' },
    ['@punctuation.bracket'] = { link = '@punctuation' },
    ['@punctuation.special'] = { link = '@punctuation' },
    ['@comment'] = { link = 'Comment' },
    ['@comment.documentation'] = { link = '@comment' },
    ['@comment.error'] = { link = 'DiagnosticError' },
    ['@comment.warning'] = { link = 'DiagnosticWarn' },
    ['@comment.todo'] = { link = 'Todo' },
    ['@comment.note'] = { link = 'DiagnosticInfo' },
    ['@markup'] = { link = 'Special' },
    ['@markup.strong'] = { link = 'Strong' },
    ['@markup.italic'] = { link = 'Faded' },
    ['@markup.strikethrough'] = { link = 'Faded' },
    ['@markup.underline'] = { link = 'Underlined' },
    ['@markup.heading'] = { link = 'Strong' },
    ['@markup.heading.1'] = { link = 'Strong' },
    ['@markup.heading.2'] = { link = 'Strong' },
    ['@markup.heading.3'] = { link = 'Strong' },
    ['@markup.heading.4'] = { link = 'Strong' },
    ['@markup.heading.5'] = { link = 'Strong' },
    ['@markup.heading.6'] = { link = 'Strong' },
    ['@markup.quote'] = { link = 'Faded' },
    ['@markup.math'] = { link = 'Faded' },
    ['@markup.link'] = { link = 'Link' },
    ['@markup.link.label'] = { link = 'Label' },
    ['@markup.link.url'] = { link = 'Underlined' },
    ['@markup.raw'] = { link = 'Faded' },
    ['@markup.raw.block'] = { link = '@markup.raw' },
    ['@markup.list'] = { link = 'Faded' },
    ['@markup.list.checked'] = { link = '@markup.list' },
    ['@markup.list.unchecked'] = { link = '@markup.list' },
    ['@diff.plus'] = { link = 'DiffAdd' },
    ['@diff.minus'] = { link = 'DiffDelete'},
    ['@diff.delta'] = { link = 'DiffChange' },
    ['@tag'] = { link = 'Tag' },
    ['@tag.builtin'] = { link = 'Special' },
    ['@tag.attribute'] = { link = '@tag' },
    ['@tag.delimiter'] = { link = '@tag' },
  }
  -- TODO https://neovim.io/doc/user/lsp.html#lsp-semantic-highlight
  -- TODO https://neovim.io/doc/user/lsp.html#lsp-highlight
  local groups_tbl = {
    Normal = { bg = palette.bg, fg = palette.fg },
    Critical = { bg = palette.critical, fg = palette.bg },
    Popout = { fg = palette.popout },
    Strong = { fg = palette.strong, bold = true },
    Salient = { fg = palette.salient },
    Faded = { fg = palette.faded },
    Subtle = { bg = palette.subtle },
  }
  merge_tbl(highlight_groups, groups_tbl)
  merge_tbl(syntax_groups, groups_tbl)
  merge_tbl(diagnostic_highlights, groups_tbl)
  merge_tbl(treesitter_highlight_groups, groups_tbl)
  for name, map in pairs(groups_tbl) do
    set_hl(name, map)
  end
end

return groups
